routes/web.php
<?php

use App\Http\Controllers\Admin\BankAccountController;
use App\Http\Controllers\Admin\ClaimController as AdminClaimController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\Documents\DocumentController;
use App\Http\Controllers\Admin\Master\BankController;
use App\Http\Controllers\Admin\Master\ClaimController;
use App\Http\Controllers\Admin\Master\GenderController;
use App\Http\Controllers\Admin\Master\JobController;
use App\Http\Controllers\Admin\Master\ProductController;
use App\Http\Controllers\Admin\Master\ProductKnowledgeController;
use App\Http\Controllers\Admin\PolicyController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ReportDanamonController;
use App\Http\Controllers\Admin\RolePermission\PermissionsController;
use App\Http\Controllers\Admin\RolePermission\RolesController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Claim\ClaimImageController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaterkitController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\ImageViewController;
use App\Http\Controllers\Pemrek\Account\AccountController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/a', [StaterkitController::class, 'home'])->name('home');
// Route::get('home', [StaterkitController::class, 'home'])->name('home');
// Route Components
Route::get('layouts/collapsed-menu', [StaterkitController::class, 'collapsed_menu'])->name('collapsed-menu');
Route::get('layouts/full', [StaterkitController::class, 'layout_full'])->name('layout-full');
Route::get('layouts/without-menu', [StaterkitController::class, 'without_menu'])->name('without-menu');
Route::get('layouts/empty', [StaterkitController::class, 'layout_empty'])->name('layout-empty');
Route::get('layouts/blank', [StaterkitController::class, 'layout_blank'])->name('layout-blank');

// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);
Route::get('/', [DashboardController::class, 'admin'])->name('dashboard');
Route::get('/documents', [DocumentController::class, 'index'])->name('document.index');
Route::group(['middleware' => ['auth', 'role:super-admin']], function () {
    //

    Route::prefix('admin')->group(function () {
        Route::resource('role', RolesController::class);
        Route::resource('permission', PermissionsController::class);

        Route::group(['prefix' => 'datatables'], function () {
            Route::get('/permission/all', [PermissionsController::class, 'data'])->name('permission.data');
            Route::get('/role/all', [RolesController::class, 'data'])->name('role.data');
            Route::get('/bank/all', [BankController::class, 'data'])->name('bank.data');
        });
    });
});

Auth::routes();

resources/views/content/_partials/_modals/modal-add-new-address.blade.php
<!-- add new address modal -->
<div class="modal fade" id="addNewAddressModal" tabindex="-1" aria-labelledby="addNewAddressTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pb-5 px-sm-4 mx-50">
        <h1 class="address-title text-center mb-1" id="addNewAddressTitle">Add New Address</h1>
        <p class="address-subtitle text-center mb-2 pb-75">Add address for billing address</p>

        <form id="addNewAddressForm" class="row gy-1 gx-2" onsubmit="return false">
          <div class="col-12">
            <div class="row custom-options-checkable">
              <div class="col-md-6 mb-md-0 mb-2">
                <input
                  class="custom-option-item-check"
                  id="homeAddressRadio"
                  type="radio"
                  name="newAddress"
                  value="HomeAddress"
                  checked
                />
                <label for="homeAddressRadio" class="custom-option-item px-2 py-1">
                  <span class="d-flex align-items-center mb-50">
                    <i data-feather="home" class="font-medium-4 me-50"></i>
                    <span class="custom-option-item-title h4 fw-bolder mb-0">Home</span>
                  </span>
                  <span class="d-block">Delivery time (7am – 9pm)</span>
                </label>
              </div>
              <div class="col-md-6 mb-md-0 mb-2">
                <input
                  class="custom-option-item-check"
                  id="officeAddressRadio"
                  type="radio"
                  name="newAddress"
                  value="OfficeAddress"
                />
                <label for="officeAddressRadio" class="custom-option-item px-2 py-1">
                  <span class="d-flex align-items-center mb-50">
                    <i data-feather="briefcase" class="font-medium-4 me-50"></i>
                    <span class="custom-option-item-title h4 fw-bolder mb-0">Office</span>
                  </span>
                  <span class="d-block">Delivery time (10am – 6pm)</span>
                </label>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6">
            <label class="form-label" for="modalAddressFirstName">First Name</label>
            <input
              type="text"
              id="modalAddressFirstName"
              name="modalAddressFirstName"
              class="form-control"
              placeholder="John"
              data-msg="Please enter your first name"
            />
          </div>
          <div class="col-12 col-md-6">
            <label class="form-label" for="modalAddressLastName">Last Name</label>
            <input
              type="text"
              id="modalAddressLastName"
              name="modalAddressLastName"
              class="form-control"
              placeholder="Doe"
              data-msg="Please enter your last name"
            />
          </div>
          <div class="col-12">
            <label class="form-label" for="modalAddressCountry">Country</label>
            <select id="modalAddressCountry" name="modalAddressCountry" class="select2 form-select">
              <option value="">Select a Country</option>
              <option value="Australia">Australia</option>
              <option value="Bangladesh">Bangladesh</option>
              <option value="Belarus">Belarus</option>
              <option value="Brazil">Brazil</option>
              <option value="Canada">Canada</option>
              <option value="China">China</option>
              <option value="France">France</option>
              <option value="Germany">Germany</option>
              <option value="India">India</option>
              <option value="Indonesia">Indonesia</option>
              <option value="Israel">Israel</option>
              <option value="Italy">Italy</option>
              <option value="Japan">Japan</option>
              <option value="Korea">Korea, Republic of</option>
              <option value="Mexico">Mexico</option>
              <option value="Philippines">Philippines</option>
              <option value="Russia">Russian Federation</option>
              <option value="South Africa">South Africa</option>
              <option value="Thailand">Thailand</option>
              <option value="Turkey">Turkey</option>
              <option value="Ukraine">Ukraine</option>
              <option value="United Arab Emirates">United Arab Emirates</option>
              <option value="United Kingdom">United Kingdom</option>
              <option value="United States">United States</option>
            </select>
          </div>
          <div class="col-12">
            <label class="form-label" for="modalAddressAddress1">Address Line 1</label>
            <input
              type="text"
              id="modalAddressAddress1"
              name="modalAddressAddress1"
              class="form-control"
              placeholder="12, Business Park"
            />
          </div>
          <div class="col-12">
            <label class="form-label" for="modalAddressAddress2">Address Line 2</label>
            <input
              type="text"
              id="modalAddressAddress2"
              name="modalAddressAddress2"
              class="form-control"
              placeholder="Mall Road"
            />
          </div>
          <div class="col-12">
            <label class="form-label" for="modalAddressTown">Town</label>
            <input
              type="text"
              id="modalAddressTown"
              name="modalAddressTown"
              class="form-control"
              placeholder="Los Angeles"
            />
          </div>
          <div class="col-12 col-md-6">
            <label class="form-label" for="modalAddressState">State / Province</label>
            <input
              type="text"
              id="modalAddressState"
              name="modalAddressState"
              class="form-control"
              placeholder="California"
            />
          </div>
          <div class="col-12 col-md-6">
            <label class="form-label" for="modalAddressZipCode">Zip Code</label>
            <input
              type="text"
              id="modalAddressZipCode"
              name="modalAddressZipCode"
              class="form-control"
              placeholder="99950"
            />
          </div>
          <div class="col-12">
            <div class="d-flex align-items-center">
              <div class="form-check form-switch form-check-primary me-25">
                <input type="checkbox" class="form-check-input" id="useAsBillingAddress" checked />
                <label class="form-check-label" for="useAsBillingAddress">
                  <span class="switch-icon-left"><i data-feather="check"></i></span>
                  <span class="switch-icon-right"><i data-feather="x"></i></span>
                </label>
              </div>
              <label class="form-check-label fw-bolder" for="useAsBillingAddress">Use as a billing address?</label>
            </div>
          </div>
          <div class="col-12 text-center">
            <button type="submit" class="btn btn-primary me-1 mt-2">Submit</button>
            <button type="reset" class="btn btn-outline-secondary mt-2" data-bs-dismiss="modal" aria-label="Close">
              Discard
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- / add new address modal -->

resources/views/content/_partials/_modals/modal-add-new-cc.blade.php
<!-- add new card modal  -->
<div class="modal fade" id="addNewCard" tabindex="-1" aria-labelledby="addNewCardTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body px-sm-5 mx-50 pb-5">
        <h1 class="text-center mb-1" id="addNewCardTitle">Add New Card</h1>
        <p class="text-center">Add card for future billing</p>

        <!-- form -->
        <form id="addNewCardValidation" class="row gy-1 gx-2 mt-75" onsubmit="return false">
          <div class="col-12">
            <label class="form-label" for="modalAddCardNumber">Card Number</label>
            <div class="input-group input-group-merge">
              <input
                id="modalAddCardNumber"
                name="modalAddCard"
                class="form-control add-credit-card-mask"
                type="text"
                placeholder="1356 3215 6548 7898"
                aria-describedby="modalAddCard2"
                data-msg="Please enter your credit card number"
              />
              <span class="input-group-text cursor-pointer p-25" id="modalAddCard2">
                <span class="add-card-type"></span>
              </span>
            </div>
          </div>

          <div class="col-md-6">
            <label class="form-label" for="modalAddCardName">Name On Card</label>
            <input type="text" id="modalAddCardName" class="form-control" placeholder="John Doe" />
          </div>

          <div class="col-6 col-md-3">
            <label class="form-label" for="modalAddCardExpiryDate">Exp. Date</label>
            <input
              type="text"
              id="modalAddCardExpiryDate"
              class="form-control add-expiry-date-mask"
              placeholder="MM/YY"
            />
          </div>

          <div class="col-6 col-md-3">
            <label class="form-label" for="modalAddCardCvv">CVV</label>
            <input
              type="text"
              id="modalAddCardCvv"
              class="form-control add-cvv-code-mask"
              maxlength="3"
              placeholder="654"
            />
          </div>

          <div class="col-12">
            <div class="d-flex align-items-center">
              <div class="form-check form-switch form-check-primary me-25">
                <input type="checkbox" class="form-check-input" id="saveCard" checked />
                <label class="form-check-label" for="saveCard">
                  <span class="switch-icon-left"><i data-feather="check"></i></span>
                  <span class="switch-icon-right"><i data-feather="x"></i></span>
                </label>
              </div>
              <label class="form-check-label fw-bolder" for="saveCard">Save Card for future billing?</label>
            </div>
          </div>

          <div class="col-12 text-center">
            <button type="submit" class="btn btn-primary me-1 mt-1">Submit</button>
            <button type="reset" class="btn btn-outline-secondary mt-1" data-bs-dismiss="modal" aria-label="Close">
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!--/ add new card modal  -->

resources/views/content/_partials/_modals/modal-add-permission.blade.php
<!-- Add Permission Modal -->
<div class="modal fade" id="addPermissionModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body px-sm-5 pb-5">
        <div class="text-center mb-2">
          <h1 class="mb-1">Add New Permission</h1>
          <p>Permissions you may use and assign to your users.</p>
        </div>
        <form action="{{ route('permission.store') }}" method="POST" id="addPermissionForm" class="row">
            @csrf
          <div class="col-12">
            <label class="form-label" for="modalPermissionName">Permission Name</label>
            <input
              type="text"
              id="modalPermissionName"
              name="name"
              class="form-control"
              placeholder="Permission Name"
              autofocus
              data-msg="Please enter permission name"
            />
          </div>
          {{-- <div class="col-12 mt-75">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="corePermission" />
              <label class="form-check-label" for="corePermission"> Set as core permission </label>
            </div>
          </div> --}}
          <div class="col-12 text-center">
            <button type="submit" class="btn btn-primary mt-2 me-1">Create Permission</button>
            <button type="reset" class="btn btn-outline-secondary mt-2" data-bs-dismiss="modal" aria-label="Close">
              Discard
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!--/ Add Permission Modal -->

resources/views/content/_partials/_modals/modal-add-role.blade.php
<!-- Add Role Modal -->
<div class="modal fade" id="addRoleModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body px-5 pb-5">
        <div class="text-center mb-4">
          <h1 class="role-title">Add New Role</h1>
          <p>Set role permissions</p>
        </div>
        <!-- Add role form -->
        <form id="addRoleForm" class="row" onsubmit="return false">
          <div class="col-12">
            <label class="form-label" for="modalRoleName">Role Name</label>
            <input
              type="text"
              id="modalRoleName"
              name="modalRoleName"
              class="form-control"
              placeholder="Enter role name"
              tabindex="-1"
              data-msg="Please enter role name"
            />
          </div>
          <div class="col-12">
            <h4 class="mt-2 pt-50">Role Permissions</h4>
            <!-- Permission table -->
            <div class="table-responsive">
              <table class="table table-flush-spacing">
                <tbody>
                  <tr>
                    <td class="text-nowrap fw-bolder">
                      Administrator Access
                      <span data-bs-toggle="tooltip" data-bs-placement="top" title="Allows a full access to the system">
                        <i data-feather="info"></i>
                      </span>
                    </td>
                    <td>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="selectAll" />
                        <label class="form-check-label" for="selectAll"> Select All </label>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">User Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="userManagementRead" />
                          <label class="form-check-label" for="userManagementRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="userManagementWrite" />
                          <label class="form-check-label" for="userManagementWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="userManagementCreate" />
                          <label class="form-check-label" for="userManagementCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Content Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="contentManagementRead" />
                          <label class="form-check-label" for="contentManagementRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="contentManagementWrite" />
                          <label class="form-check-label" for="contentManagementWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="contentManagementCreate" />
                          <label class="form-check-label" for="contentManagementCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Disputes Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="dispManagementRead" />
                          <label class="form-check-label" for="dispManagementRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="dispManagementWrite" />
                          <label class="form-check-label" for="dispManagementWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="dispManagementCreate" />
                          <label class="form-check-label" for="dispManagementCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Database Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="dbManagementRead" />
                          <label class="form-check-label" for="dbManagementRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="dbManagementWrite" />
                          <label class="form-check-label" for="dbManagementWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="dbManagementCreate" />
                          <label class="form-check-label" for="dbManagementCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Financial Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="finManagementRead" />
                          <label class="form-check-label" for="finManagementRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="finManagementWrite" />
                          <label class="form-check-label" for="finManagementWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="finManagementCreate" />
                          <label class="form-check-label" for="finManagementCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Reporting</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="reportingRead" />
                          <label class="form-check-label" for="reportingRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="reportingWrite" />
                          <label class="form-check-label" for="reportingWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="reportingCreate" />
                          <label class="form-check-label" for="reportingCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">API Control</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="apiRead" />
                          <label class="form-check-label" for="apiRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="apiWrite" />
                          <label class="form-check-label" for="apiWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="apiCreate" />
                          <label class="form-check-label" for="apiCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Repository Management</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="repoRead" />
                          <label class="form-check-label" for="repoRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="repoWrite" />
                          <label class="form-check-label" for="repoWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="repoCreate" />
                          <label class="form-check-label" for="repoCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td class="text-nowrap fw-bolder">Payroll</td>
                    <td>
                      <div class="d-flex">
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="payrollRead" />
                          <label class="form-check-label" for="payrollRead"> Read </label>
                        </div>
                        <div class="form-check me-3 me-lg-5">
                          <input class="form-check-input" type="checkbox" id="payrollWrite" />
                          <label class="form-check-label" for="payrollWrite"> Write </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="payrollCreate" />
                          <label class="form-check-label" for="payrollCreate"> Create </label>
                        </div>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <!-- Permission table -->
          </div>
          <div class="col-12 text-center mt-2">
            <button type="submit" class="btn btn-primary me-1">Submit</button>
            <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">
              Discard
            </button>
          </div>
        </form>
        <!--/ Add role form -->
      </div>
    </div>
  </div>
</div>
<!--/ Add Role Modal -->

resources/views/content/_partials/_modals/modal-edit-permission.blade.php
<!-- Edit Permission Modal -->
<div class="modal fade" id="editPermissionModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body p-3 pt-0">
        <div class="text-center mb-2">
          <h1 class="mb-1">Edit Permission</h1>
          <p>Edit permission as per your requirements.</p>
        </div>

        <div class="alert alert-warning" role="alert">
          <h6 class="alert-heading">Warning!</h6>
          <div class="alert-body">
            By editing the permission name, you might break the system permissions functionality. Please ensure you're
            absolutely certain before proceeding.
          </div>
        </div>

        <form id="editPermissionForm" class="row">
          <div class="col-sm-9">
            <label class="form-label" for="editPermissionName">Permission Name</label>
            <input
              type="text"
              id="editPermissionName"
              name="editPermissionName"
              class="form-control"
              placeholder="Enter a permission name"
              tabindex="-1"
              data-msg="Please enter permission name"
            />
          </div>
          <div class="col-sm-3 ps-sm-0">
            <button type="button" id="update_data" class="btn btn-primary mt-2">Update</button>
          </div>
          {{-- <div class="col-12 mt-75">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="editCorePermission" />
              <label class="form-check-label" for="editCorePermission"> Set as core permission </label>
            </div>
          </div> --}}
        </form>
      </div>
    </div>
  </div>
</div>
<!--/ Edit Permission Modal -->